disabled_rules: # rule identifiers to exclude from running
    - type_name
    - line_length
    - identifier_name
    - unused_capture_list
    - trailing_whitespace
    - empty_enum_arguments
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
